language: ruby
sudo: false
cache:
  directories:
  - vendor/bundle
  - wget_cache
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
bundler_args: --without acceptance
script:
  - bundle exec rake syntax
  - bundle exec rake lint
  - bundle exec rake spec
notifications:
  email:
    - biemond@gmail.com
    - junior.jairo1@gmail.com
env:
  - PUPPET_VERSION=4.4.2
  - PUPPET_VERSION=4.6.2
  - PUPPET_VERSION=4.8.2
  - PUPPET_VERSION=4.9.4
  - PUPPET_VERSION=4.10.4
matrix:
  include:
    - rvm: 2.3.3
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      sudo: required
      group: edge
      bundler_args: --with acceptance
    - rvm: 2.3.3
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-7 bundle
      script: bundle exec rake beaker
      services: docker
      sudo: required
      group: edge
      bundler_args: --with acceptance
    - rvm: 2.3.3
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-1404 bundle
      script: bundle exec rake beaker
      services: docker
      sudo: required
      group: edge
      bundler_args: --with acceptance
    - rvm: 2.3.3
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent TEST_profile=wildfly:10.1.0 BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      sudo: required
      group: edge
      bundler_args: --with acceptance
    - rvm: 2.3.3
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent TEST_profile=wildfly:10.1.0 BEAKER_debug=true BEAKER_set=docker/debian-7
      script: bundle exec rake beaker
      services: docker
      sudo: required
      group: edge
      bundler_args: --with acceptance
    - rvm: 2.3.3
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent TEST_profile=wildfly:10.1.0 BEAKER_debug=true BEAKER_set=docker/ubuntu-1404
      script: bundle exec rake beaker
      services: docker
      sudo: required
      group: edge
      bundler_args: --with acceptance
